
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ichirou/Desktop/HW_CAM-main/.venv/Lib/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
